/* Shared types for run workflow step handlers. */

import type { AppliedOpPlan, DomWriter } from "~/core/dom/index.ts";
import type { DocNode } from "~/core/dom/types.ts";
import type { Gdoc } from "~/core/gdoc.ts";
import type { DrivePermission, GwsClient } from "~/core/gws.ts";
import type { GoogleDoc } from "~/core/types.ts";
import type { ApplyHighlightDocJson, GdocsmithStepInputInternal, PageSetup } from "~/core/workflowTypes.ts";

export type { WorkflowStepKind } from "~/core/workflowTypes.ts";

/** Pending write buffer for batched mutations on a specific document tab. */
export type PendingWriterEntry = {
  /** Chained afterend insertions map. */
  afterendTails: Map<number, DocNode>;
  /** Snapshot of raw GoogleDoc data when writer session started. */
  doc: GoogleDoc;
  /** Named anchors map established by as: directives. */
  namedAnchors: Map<string, DocNode>;
  /** Recorded op execution preview plans. */
  plans: AppliedOpPlan[];
  /** Chained root anchor map. */
  rootAnchors: Map<number, number>;
  /** Active DOM writer accumulating surgical mutations. */
  writer: DomWriter;
};

/** Context tracked for an active or open document session. */
export type OpenDocContext = {
  /** Document alias used in workflow steps. */
  alias: string;
  /** Real or virtual Google Docs document identifier. */
  docId: string;
  /** Active Gdoc instance. */
  gdoc: Gdoc;
  /** True when document is an ephemeral virtual in-memory document. */
  isVirtual?: boolean;
  /** Buffered in-memory DOM writers accumulating surgical mutations per tab. */
  pendingWriters?: Map<string, PendingWriterEntry>;
  /** Drive permissions for document. */
  permissions?: DrivePermission[];
  /** Pinned Drive revision ID. */
  pinnedRevisionId?: string;
  /** Document title. */
  title: string;
};

/** In-memory dry-run node tape attached to a loaded Gdoc. */
export type SimulatedGdoc = Gdoc & {
  simulatedNodes?: import("~/core/dom/types.ts").DocNode[];
  simulatedTabs?: Map<string, import("~/core/dom/types.ts").DocNode[]>;
};

/** Mutable runtime state shared across workflow step handlers. */
export type ApplyScriptRuntime = {
  activeDocAlias: string | undefined;
  aliasMap: Map<string, string>;
  aliasResolve: (val?: string) => string | undefined;
  client: GwsClient;
  createdHighlights: Map<string, ApplyHighlightDocJson>;
  docIdToAlias: Map<string, string>;
  dumpStore: Map<string, unknown>;
  dumped: Record<string, unknown>;
  dryRun: boolean;
  force: boolean;
  initialMarkdownStates: Map<string, string>;
  openDocResolve: (rawDocRef?: string) => OpenDocContext;
  openDocs: Map<string, OpenDocContext>;
  /** Document-level page geometry from the run document (applied once after steps). */
  pageSetup?: PageSetup;
  /** Documents pre-fetched during preflight validation. */
  preloadedDocs: Map<string, Gdoc>;
  /** Aliases generated by query steps (cannot be used as mutation anchors). */
  queryAliases: Set<string>;
  stepsExecuted: number;
  tabMarkdownCapture: (ctx: OpenDocContext, tabId: string) => Promise<string>;
};

/** One workflow step handler. */
export type WorkflowStepHandler<TStep extends GdocsmithStepInputInternal = any> = (
  runtime: ApplyScriptRuntime,
  stepIndex: number,
  step: TStep,
) => Promise<void>;
