// Auto-generated by argsbarg schemagen — do not edit by hand.

import GdocsmithDocumentSchemaJson from "./GdocsmithDocumentSchema.json";
import GdocsmithJsonOutputSchemaJson from "./GdocsmithJsonOutputSchema.json";

export const GdocsmithDocumentSchema = GdocsmithDocumentSchemaJson as Record<string, unknown>;

export const GdocsmithJsonOutputSchema = GdocsmithJsonOutputSchemaJson as Record<string, unknown>;
