// Auto-generated by argsbarg schemagen — do not edit by hand.

import StatusJsonOutputSchemaJson from "./StatusJsonOutputSchema.json";

export const StatusJsonOutputSchema = StatusJsonOutputSchemaJson as Record<string, unknown>;
